<option value="COMMERCE">COMMERCE</option>
<option value="FINANCIAL ACCOUNTING">FINANCIAL ACCOUNTING</option>
<option value="CHRISTIAN RELIGIOUS STUDIES">CHRISTIAN RELIGIOUS STUDIES</option>
<option value="ECONOMICS">ECONOMICS</option>
<option value="GEOGRAPHY">GEOGRAPHY</option>
<option value="GOVERNMENT">GOVERNMENT</option>
<option value="ISLAMIC STUDIES">ISLAMIC STUDIES</option>
<option value="LITERATURE IN ENGLISH">LITERATURE IN ENGLISH</option>
<option value="CIVIC EDUCATION">CIVIC EDUCATION</option>
<option value="ENGLISH LANGUAGE">ENGLISH LANGUAGE</option>
<option value="HAUSA">HAUSA</option>
<option value="IGBO">IGBO</option>
<option value="YORUBA">YORUBA</option>
<option value="FURTHER MATHEMATICS">FURTHER MATHEMATICS</option>
<option value="GENERAL MATHEMATICS">GENERAL MATHEMATICS</option>
<option value="AGRICULTURAL SCIENCE">AGRICULTURAL SCIENCE</option>
<option value="BIOLOGY">BIOLOGY</option>
<option value="CHEMISTRY">CHEMISTRY</option>
<option value="PHYSICS">PHYSICS</option>
